postgresql:
  postgresqlPassword: "R3s3tM3N0w!"

configOverrides:
  secret: |
    SECRET_KEY = 'mz6BCsrYnGgJ5zM7S+zZRtXS32JaFFddiYZ2h16neuK3WSMxIqe5j5EC'

image:
  repository: lscsde/apache-superset
  tag: 0.1.2
  imagePullPolicy: Always

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect : "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    xlscsde.nhs.uk/dns-record: superset${environment_dns_suffix}
  tls:
  - hosts:
    - ${environment_dns_prefix}superset${environment_dns_suffix}.${private_dnz_zone}
    secretName: ${environment_dns_prefix}superset${environment_dns_suffix}.${private_dnz_zone}-tls

  hosts:
  - ${environment_dns_prefix}superset${environment_dns_suffix}.${private_dnz_zone}
  