apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset
  namespace: ${superset_namespace}
spec:
  targetNamespace: ${superset_namespace}
  releaseName: superset
  chart:
    spec:
      chart: superset
      version: ${superset_chart_version}
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: ${superset_namespace}
  interval: 1m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: superset-config
      