apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${environment_dns_prefix}superset${environment_dns_suffix}.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Wildcard Certificate"
spec:
  name: ${environment_dns_prefix}superset${environment_dns_suffix}.${private_dnz_zone}-tls
  type: kubernetes.io/tls
  secrets:
  - from: WildcardCertificate
    to: tls.crt
  - from: WildcardCertificateKey
    to: tls.key
---
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: superset-auth
  annotations:
    xlscsde.nhs.uk/secretUsage: "Authentication/Authorization"
spec:
  name: superset-auth
  type: Opaque
  secrets:
  - from: ApacheSupersetAppRegistrationClientSecret
    to: CLIENT_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-env
type: Opaque
stringData:
  DB_HOST: ${postgresql_server}
  DB_NAME: superset
  DB_PASS: superset
  DB_PORT: "5432"
  DB_USER: superset@${postgresql_server}
  REDIS_CELERY_DB: "0"
  REDIS_DB: "1"
  REDIS_HOST: superset-redis-h
  REDIS_PORT: "6379"
  REDIS_PROTO: redis
  REDIS_USER: ""