name: Create Release Branch from Main

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  package:
    uses: lsc-sde/lsc-sde/.github/workflows/flux-release.yaml@main
    with:
      directory: products/sde-3rd-party/superset/iac-flux-apache-superset
      yamlPath: superset
    secrets: inherit
